const Border = () => {
    return ( 
        <div>
            <p className="tab">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum suspendisse ultrices gravida dictum. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Pretium lectus quam id leo in vitae turpis massa. Convallis aenean et tortor at risus viverra. Convallis convallis tellus id interdum. Pulvinar neque laoreet suspendisse interdum consectetur. Fusce id velit ut tortor pretium. Est ultricies integer quis auctor elit sed vulputate mi sit. Nisi scelerisque eu ultrices vitae auctor eu. Elementum integer enim neque volutpat ac tincidunt. Morbi tempus iaculis urna id volutpat. Faucibus in ornare quam viverra orci sagittis eu volutpat. Varius sit amet mattis vulputate enim. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Bibendum arcu vitae elementum curabitur.
            <p className="tab">Aenean et tortor at risus viverra adipiscing. Integer enim neque volutpat ac tincidunt vitae semper quis. Nunc sed blandit libero volutpat sed cras ornare arcu dui. Penatibus et magnis dis parturient montes. Est velit egestas dui id ornare arcu odio ut. Velit euismod in pellentesque massa. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Velit laoreet id donec ultrices tincidunt. Mi in nulla posuere sollicitudin aliquam. Velit egestas dui id ornare arcu odio ut sem nulla.</p>
            <p className="tab">Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Quis auctor elit sed vulputate mi sit amet mauris commodo. Etiam tempor orci eu lobortis elementum nibh tellus. Nam at lectus urna duis. Quis hendrerit dolor magna eget est lorem. Nunc pulvinar sapien et ligula ullamcorper malesuada. Purus in mollis nunc sed id. Odio facilisis mauris sit amet massa. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Vestibulum lorem sed risus ultricies. Turpis egestas integer eget aliquet.</p></p>
        </div>
     );
}
 
export default Border;